# Generated by Django 5.2.15 on 2026-06-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_embedding_note_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
