# Generated by Django 5.2.15 on 2026-06-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_embedding_alter_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('AI', 'AI'), ('ML', 'Machine Learning'), ('DL', 'Deep Learning'), ('NLP', 'NLP'), ('CV', 'Computer Vision'), ('Programming', 'Programming'), ('Other', 'Other')], default='Other', max_length=30),
        ),
        migrations.AddField(
            model_name='note',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
